language: python

python:
  - 2.7
  - 3.5
  - 3.6

# While python3.7 is not supported by default dist...
matrix:
    include:
      - sudo: required
        dist: xenial
        python: 3.7
        env: EVM_EMACS=emacs-24.4-travis
      - sudo: required
        dist: xenial
        python: 3.7
        env: EVM_EMACS=emacs-24.5-travis
      - sudo: required
        dist: xenial
        python: 3.7
        env: EVM_EMACS=emacs-25.1-travis
      - sudo: required
        dist: xenial
        python: 3.7
        env: EVM_EMACS=emacs-25.2-travis
      - sudo: required
        dist: xenial
        python: 3.7
        env: EVM_EMACS=emacs-25.3-travis
      # emacs 26.1 doesn't seem to start on xenial
      # - sudo: required
      #   dist: xenial
      #   python: 3.7
      #   env: EVM_EMACS=emacs-26.1-travis

env:
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-25.3-travis
  # - EVM_EMACS=emacs-26.1-travis
before_install:
  # - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > travis.sh && source ./travis.sh
  - source ./travis-evm-cask.sh
  - evm install $EVM_EMACS --use --skip
  - cask --verbose        # verbose only needed because of cask bug
install:
  - pip install -r requirements.txt --upgrade
  - pip install -r requirements-rpc.txt --upgrade
  - pip install -r requirements-dev.txt --upgrade
  - if [[ "$TRAVIS_PYTHON_VERSION" > 3.5 ]] ; then
      pip install -r requirements-rpc3.6.txt --upgrade ;
    fi
  - if [[ "$TRAVIS_PYTHON_VERSION" < 3 ]] ; then
      pip install -r requirements-dev2.txt --upgrade ;
    fi
  - pip install importmagic
  - pip install coveralls
  - virtualenv ~/.virtualenvs/elpy-test-venv
script:
  - nosetests
  - PYTHONPATH="`pwd`" cask exec ert-runner
after_success:
  - coverage run -m nose.__main__
  - coveralls
